### ISSUE TITLE
Add packmol back to pins?

### ISSUE THREAD

**Issue by lilyminium** [conda-forge/openff-evaluator-feedstock#45] opened 2024-09-06 05:09 UTC
### Comment:

>         # 23.6 includes packmol in the ambertools package, if users
>         # have older versions installed, they might need to install
>         # packmol (the standalone conda-forge package) themselves

I just got bit by this in creating a new environment that picked up 0.4.9. Would it be possible to add this pin back in or would it conflict with ambertools?  Evaluator can be  installed without ambertools at all (e.g. with openff-toolkit-base), and packmol seems like an important component.

**Comment by mattwthompson** [comment] 2024-09-09 16:18
I couldn't figure out a way to bring _one_ of them down conditionally; if we add it back, AmberTools 23.6+ cannot be installed in the same environment. If we add it back, that means `ambertools <23.6` which will cause other issues in time (or already, I don't know). What I want to do is add package-based selectors into `run_constrained:`, but I don't think that's possible.

The problem is https://github.com/conda-forge/ambertools-feedstock/pull/137/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR95, which I tried to work around in #41, some variant of which landed in #43.

Any ideas?

**Comment by lilyminium** [comment] 2024-09-10 01:17
Ahhh, I see, the ambertools pin is super inconvenient. So we basically want a scenario where by default openff-evaluator installs `packmol`, except if ambertools>22 is present in the environment.

One manual workaround is two different builds with different dependencies pinned, one with packmol installed and ambertools constrained to <22, and one that installs `ambertools>22,<24`. The user would just pick up whichever build is necessary for their environment.

This could maybe be automated with [variants in a conda_build_config.yaml](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files) file, but I spent half an hour scrolling through the docs and still can't say for sure if it's set up for this case.

Largely though, while I think this is a real issue (as users can't just install `openff-evaluator` and start running a full fit without separately installing packmol too), the workaround of manually specifying packmol is much easier than playing around with conda here, so happy to also just leave it open.

**Comment by mattwthompson** [comment] 2024-09-10 16:46
My opinion seems to have changed today, leaning in favor of just adding it back. ( I wonder what it'll be tomorrow ... ?) I assume you don't need anything specific from AmberTools 23.6, or at least I'm unaware of major feature changes outside of packaging/compatibility.

Really, it'd be wonderful to have something like https://github.com/conda-forge/ambertools-feedstock/issues/138; we'd be able to install just Packmol from there without bringing down everything else

**Comment by mattwthompson** [comment] 2024-09-12 15:38
I'm even more in favor of "just add it back" now; the upside is clear in that it ensures the conda package actually pulls down what's needed.

The key downside, as I see it, is that Evaluator is stuck on AmberTools 23.6 and older (presumably as old as 22). If Evaluator, or something else in the OpenFF stack, _truly_ needs 23.6+ or 24+ builds in the future, this will need to be re-evaluated since (as above) there doesn't seem to be an easy way to conditionally skip a dependency if a non-dependency is present elsewhere in the environment. I think on that day, the worst outcome is that we'll just have to drop it as a dependency and push the burden to users (a.k.a. the current state).

**Closed** 2024-09-12 16:06 UTC
Labels: question

**Comment by lilyminium** [comment] 2024-09-12 22:26
Thanks Matt! I'm happy to go with this. I think the one downside to this approach is that the fix to my issue was fairly obvious -- to install packmol -- whereas to a user it may be less clear why packmol is blocking AmberTools 23 and what to do about it. I still don't really see an easy solution though, other than the multiple builds, and at least openff evaluator in a new environment works out of the box.  Thanks for the fix!
